apiVersion: v1
kind: Service
metadata:
  name: apollo
spec:
  ports:
  - name: ui-port
    port: 8080
    targetPort: 8080
  - name: apollo-port
    port: 8070
    targetPort: 8070
  selector:
    app: apollo
  clusterIP: None
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: apollo
spec:
  selector:
    matchLabels:
      app: apollo
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: apollo
    spec:
      containers:
      - image: good0206/apollo:latest
        name: apollo
        env:
          # Use secret in real usage
          - name: TZ
            value: "Asia/Shanghai"
        ports:
        - containerPort: 8070
          name: apollo-port
        - containerPort: 8080
          name: ui-port